# Generated by Django 3.1.7 on 2021-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updimages',
            name='img',
            field=models.ImageField(upload_to='upd'),
        ),
    ]
