# Generated by Django 3.1.7 on 2021-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210226_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='upd'),
        ),
    ]
