# Generated by Django 3.1.7 on 2021-03-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210226_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='updimages',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
