# Generated by Django 3.1.7 on 2021-03-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_updimages_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updimages',
            old_name='owner',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='updimages',
            name='img',
            field=models.ImageField(upload_to='upd'),
        ),
    ]
