# Generated by Django 3.1.7 on 2021-03-05 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0005_auto_20210305_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updimages',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='updimages',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
