# Generated by Django 3.1.7 on 2021-03-05 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210305_1012'),
        ('images', '0007_auto_20210305_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updimages',
            name='user',
        ),
        migrations.AddField(
            model_name='updimages',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.user_profile'),
            preserve_default=False,
        ),
    ]
