# Generated by Django 3.1.7 on 2021-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20210305_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='updimages',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
