# Generated by Django 3.1.7 on 2021-03-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_updimagestext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updimagestext',
            old_name='a',
            new_name='updimages',
        ),
    ]
