# Generated by Django 3.1.7 on 2021-03-09 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20210309_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updimages',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.updimagestext'),
        ),
    ]
